import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/Components/Header/Header";
import Footer from "./Components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pure Cordy Life Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}<Footer/></body>
    </html>
  );
}
